LLAMACPP_REPO=https://github.com/ggml-org/llama.cpp.git
LLAMACPP_REVISION=0666ad2b2b2452668733729e8b54234f5964643a
LLAMACPP_BUILD_NUMBER=10356
LLAMACPP_OS=Linux
LLAMACPP_CUDA_ROOT=/usr/local/cuda-12.8
LLAMACPP_CUDA_ARCHITECTURE=89
