MODEL_ID=gemma-4-31b
MODEL_NAME='Gemma 4 31B'

BACKEND=llamacpp

TARGET_HF_REPO=ggml-org/gemma-4-31B-it-GGUF
VARIANTS=q4-0
DEFAULT_VARIANT=q4-0

DOWNLOAD_Q4_0_FILE='gemma-4-31B-it-Q4_0.gguf'
DOWNLOAD_Q4_0_SIZE=17992313088

LLAMACPP_CONTEXT=16384
LLAMACPP_BATCH=1024
LLAMACPP_UBATCH=512
LLAMACPP_CACHE_TYPE=f16
LLAMACPP_JINJA=1
LLAMACPP_TEMPERATURE=1.0
LLAMACPP_TOP_P=0.95
LLAMACPP_TOP_K=64
